// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngest_Stream_FullMethodName = "/agent.v1.AgentIngest/Stream"
)

// AgentIngestClient is the client API for AgentIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentIngestClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchMsg, AckMsg], error)
}

type agentIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestClient(cc grpc.ClientConnInterface) AgentIngestClient {
	return &agentIngestClient{cc}
}

func (c *agentIngestClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchMsg, AckMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngest_ServiceDesc.Streams[0], AgentIngest_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchMsg, AckMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_StreamClient = grpc.BidiStreamingClient[BatchMsg, AckMsg]

// AgentIngestServer is the server API for AgentIngest service.
// All implementations must embed UnimplementedAgentIngestServer
// for forward compatibility.
type AgentIngestServer interface {
	Stream(grpc.BidiStreamingServer[BatchMsg, AckMsg]) error
	mustEmbedUnimplementedAgentIngestServer()
}

// UnimplementedAgentIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServer struct{}

func (UnimplementedAgentIngestServer) Stream(grpc.BidiStreamingServer[BatchMsg, AckMsg]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentIngestServer) mustEmbedUnimplementedAgentIngestServer() {}
func (UnimplementedAgentIngestServer) testEmbeddedByValue()                     {}

// UnsafeAgentIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServer will
// result in compilation errors.
type UnsafeAgentIngestServer interface {
	mustEmbedUnimplementedAgentIngestServer()
}

func RegisterAgentIngestServer(s grpc.ServiceRegistrar, srv AgentIngestServer) {
	// If the following call panics, it indicates UnimplementedAgentIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngest_ServiceDesc, srv)
}

func _AgentIngest_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServer).Stream(&grpc.GenericServerStream[BatchMsg, AckMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_StreamServer = grpc.BidiStreamingServer[BatchMsg, AckMsg]

// AgentIngest_ServiceDesc is the grpc.ServiceDesc for AgentIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentIngest",
	HandlerType: (*AgentIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentIngest_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
