// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Lane          string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"` // "FAST" or "STANDARD"
	SeqStart      uint64                 `protobuf:"varint,5,opt,name=seq_start,json=seqStart,proto3" json:"seq_start,omitempty"`
	SeqEnd        uint64                 `protobuf:"varint,6,opt,name=seq_end,json=seqEnd,proto3" json:"seq_end,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // opaque bytes for now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Batch) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *Batch) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Batch) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *Batch) GetSeqStart() uint64 {
	if x != nil {
		return x.SeqStart
	}
	return 0
}

func (x *Batch) GetSeqEnd() uint64 {
	if x != nil {
		return x.SeqEnd
	}
	return 0
}

func (x *Batch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lane          string                 `protobuf:"bytes,1,opt,name=lane,proto3" json:"lane,omitempty"`
	SeqEnd        uint64                 `protobuf:"varint,2,opt,name=seq_end,json=seqEnd,proto3" json:"seq_end,omitempty"`
	JsSeq         uint64                 `protobuf:"varint,3,opt,name=js_seq,json=jsSeq,proto3" json:"js_seq,omitempty"` // JetStream publish ack sequence (if available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *Ack) GetSeqEnd() uint64 {
	if x != nil {
		return x.SeqEnd
	}
	return 0
}

func (x *Ack) GetJsSeq() uint64 {
	if x != nil {
		return x.JsSeq
	}
	return 0
}

var File_proto_master_proto protoreflect.FileDescriptor

const file_proto_master_proto_rawDesc = "" +
	"\n" +
	"\x12proto/master.proto\x12\tmaster.v1\"\xc6\x01\n" +
	"\x05Batch\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\x12\x1b\n" +
	"\tseq_start\x18\x05 \x01(\x04R\bseqStart\x12\x17\n" +
	"\aseq_end\x18\x06 \x01(\x04R\x06seqEnd\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"I\n" +
	"\x03Ack\x12\x12\n" +
	"\x04lane\x18\x01 \x01(\tR\x04lane\x12\x17\n" +
	"\aseq_end\x18\x02 \x01(\x04R\x06seqEnd\x12\x15\n" +
	"\x06js_seq\x18\x03 \x01(\x04R\x05jsSeq28\n" +
	"\x06Ingest\x12.\n" +
	"\x06Stream\x12\x10.master.v1.Batch\x1a\x0e.master.v1.Ack(\x010\x01B Z\x1er-siem-agent/internal/proto/pbb\x06proto3"

var (
	file_proto_master_proto_rawDescOnce sync.Once
	file_proto_master_proto_rawDescData []byte
)

func file_proto_master_proto_rawDescGZIP() []byte {
	file_proto_master_proto_rawDescOnce.Do(func() {
		file_proto_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)))
	})
	return file_proto_master_proto_rawDescData
}

var file_proto_master_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_master_proto_goTypes = []any{
	(*Batch)(nil), // 0: master.v1.Batch
	(*Ack)(nil),   // 1: master.v1.Ack
}
var file_proto_master_proto_depIdxs = []int32{
	0, // 0: master.v1.Ingest.Stream:input_type -> master.v1.Batch
	1, // 1: master.v1.Ingest.Stream:output_type -> master.v1.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_master_proto_init() }
func file_proto_master_proto_init() {
	if File_proto_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_master_proto_goTypes,
		DependencyIndexes: file_proto_master_proto_depIdxs,
		MessageInfos:      file_proto_master_proto_msgTypes,
	}.Build()
	File_proto_master_proto = out.File
	file_proto_master_proto_goTypes = nil
	file_proto_master_proto_depIdxs = nil
}
