[rsiem_agents]
agent1 ansible_host=192.168.1.50
agent2 ansible_host=192.168.1.51

[rsiem_agents:vars]
ansible_user=khotso
ansible_become=true

# gRPC master endpoint
rsiem_master_addr=master.example.com:7777
rsiem_master_server_name=master.local
